security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
#    providers:
#        saml_provider:
#            # Basic provider instantiates a user with default roles
#            saml:
#                user_class: 'App\Security\User\User'
#                default_roles: [ 'ROLE_USER' ]
    providers:
        commongroundApplicationProvider:
            id: Conduction\CommonGroundBundle\Security\User\CommongroundApplicationProvider
        commongroundProvider:
            id: Conduction\CommonGroundBundle\Security\User\CommongroundProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|docs)/
            security: false
        # The mollie webhook does not have our API key
        webhook:
            anonymous: true
            pattern: ^/payments/mollie_webhook
            methods: [POST]
#        main:
#            anonymous: ~
#            pattern: ^/
#            saml:
#                # Match SAML attribute 'uid' with username.
#                # Uses getNameId() method by default.
#                username_attribute: uid
#                # Use the attribute's friendlyName instead of the name 
#                use_attribute_friendly_name: false
#                check_path: saml_acs
#                login_path: saml_login
#            logout:
#                path: saml_logout
        main:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: app_user_login
                check_path: app_user_login
            logout:
                path: app_user_logout
                target: app_default_index
            stateless: false
            provider: commongroundProvider
            guard:
                authenticators:
                    - App\Security\CommongroundDigidAuthenticator
                entry_point: App\Security\CommongroundDigidAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
