apiVersion: v1
entries:
  waardepapieren:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-02-02T09:17:52.4251874Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 50449e6e814680b4f6a367baa38e7d66912e07423c2694007e1f66a37417b3ca
    home: www.waardepapieren.com
    icon: www.waardepapieren.com
    name: waardepapieren
    urls:
    - waardepapieren-0.1.0.tgz
    version: 0.1.0
generated: "2021-02-02T09:17:52.4193756Z"
