apiVersion: v1
entries:
  waardepapieren:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-11-24T22:05:09.6967483Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 1f820a560a7011dc3ce83c2c11af81d07c6b305fc11c8dbffb08446d730a5e75
    home: www.waardepapieren.com
    icon: www.waardepapieren.com
    name: waardepapieren
    urls:
    - waardepapieren-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-24T22:05:09.6904563Z"
