apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-php
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-php
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-php
  replicas: {{ .Values.php.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-php
        app.kubernetes.io/part-of: {{ .Release.Name }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      volumes:
          - name: dependencies
            secret:
              secretName: {{ template "fullname" . }}-dependencies
              defaultMode: 420
          {{- if eq .Values.config.mode "digid" }}
          - name: certificates
            secret:
              {{ if .Values.security.certificate.existingSecret }}
                secretName: {{ .Values.security.certificate.existingSecret }}
              {{ else }}
                secretName: {{ template "fullname" . }}-certificate
              {{ end }}
                defaultMode: 420
          {{- end }}
      containers:
        - name: {{ .Release.Name }}-php
          image: "{{ .Values.php.image }}:{{ .Values.php.tag }}"
          imagePullPolicy: {{ .Values.php.pullPolicy }}
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /srv/api/config/packages/dependencies.yaml
              subPath: dependencies.yaml
              name: dependencies
              readOnly: true
            {{- if eq .Values.config.mode "digid" }}
            - mountPath: /var/run/certs
              name: certificates
              readOnly: true
            {{- end }}
          env:
            - name: JWT_SECRET_KEY
              value: '%kernel.project_dir%/config/jwt/private.pem'
            - name: JWT_PUBLIC_KEY
              value: '%kernel.project_dir%/config/jwt/public.pem'
            - name: JWT_PASSPHRASE
              value: 'bafe1dc254b45471754c221081f874aa'
            - name: APP_ENV
              value: 'prod'
            - name: TRUSTED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: trusted-hosts
            - name: TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: trusted-proxies
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: app-version
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: debug
            - name: APP_CACHE
              valueFrom:
                  configMapKeyRef:
                      name: {{ template "fullname" . }}
                      key: cache      
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: database-url
            - name: CORS_ALLOW_ORIGIN
              valueFrom:
                  configMapKeyRef:
                      name: {{ template "fullname" . }}
                      key: app-corsAllowOrigin
            - name: APP_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: app_application_key
            {{ if .Values.redis.enabled }}
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: redis-port
            {{- end }}
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: {{ template "fullname" . }}
            - name: APP_MODE
              valueFrom:
                  configMapKeyRef:
                      key: mode
                      name: {{ template "fullname" . }}
            {{- if (eq .Values.config.mode "digid") }}
            - name: APP_CERT
              valueFrom:
                    secretKeyRef:
                         key: certificate
                         name: {{ template "fullname" . }}
            - name: APP_KEY
              valueFrom:
                    secretKeyRef:
                        key: private_key
                        name: {{ template "fullname" . }}
            {{- end }}
            -   name: APP_SHASIGN
                valueFrom:
                    secretKeyRef:
                        name: {{ template "fullname" . }}
                        key: app_shasign
            {{- if eq .Values.config.mode "digid" }}
            -   name: SAML_PRIVATE_KEY
                valueFrom:
                    secretKeyRef:
                      {{ if .Values.security.certificate.existingSecret }}
                        name: {{ .Values.security.certificate.existingSecret }}
                      {{ else }}
                        name: {{ template "fullname" . }}-certificate
                      {{ end }}
                        key: tls.key
            -   name: SAML_X509_CERT
                valueFrom:
                    secretKeyRef:
                      {{ if .Values.security.certificate.existingSecret }}
                        name: {{ .Values.security.certificate.existingSecret }}
                      {{ else }}
                        name: {{ template "fullname" . }}-certificate
                      {{ end }}
                        key: tls.crt
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
