{{- $postgresqlServiceName := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s/%s?serverVersion=10" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword $postgresqlServiceName .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{ else if .Values.postgresql.url  }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{ else }}
  database-url:
  {{ end }}
  app_application_key: {{ .Values.security.applicationKey | b64enc | quote }}
  app_shasign: {{ .Values.security.shasign | b64enc | quote }}
  saml_private_key: {{ .Values.security.samlPrivateKey | b64enc | quote }}
  saml_x509_cert: {{ .Values.security.samlX509Cert | b64enc | quote }}

  {{- if eq .Values.config.mode "digid" }}
  certificate: {{ "/var/run/certs/digid.crt" | b64enc | quote }}
  private_key: {{ "/var/run/certs/digid.key" | b64enc | quote }}
  {{- end }}
