component_depth: 3
languages:
    - php
exclude:
    - /nlx-setup/.*
    - /resources/.*
    - /api/bin/.*
    - /api/config/.*
    - /api/docker/.*
    - /api/docs/.*
    - /api/helm/.*
    - /api/migrations/.*
    - /api/nlx-setup/.*
    - /api/public/.*
    - /api/templates/.*
    - /api/translations/.*
    - /api/var/.*
    - /api/vendor/.*
    - /api/src/Entity/.*
    - /api/src/DataFixtures/.*
    - /api/src/Repository/.*
    - /api/src/Kernel.php
test:
    include:
        - /api/tests/TrouwServiceTest.php
